### ISSUE TITLE
Modification of agent version for Lodestar

### ISSUE THREAD

**Issue by philknows** [ChainSafe/nodewatch-api#200]
## Details
Reference: https://github.com/ChainSafe/lodestar/issues/4465

Lodestar is looking to modify the agent version gossiped from the default libp2p string js-libp2p/0.36.2 to lodestar/version. We are requesting an update to your client on how you identify Lodestar nodes for better tracking and referencing of Lodestar peers on the network for debug purposes. We will not implement until it has been completed between all the various clients on the network.

## Acceptance criteria
Update crawler with how it identifies Lodestar on the network. Should detect Lodestar under `lodestar/version`.

**Comment by spacesailor24** [comment]
From my understanding, no code change is required for how the crawler parses the `UserAgent`. [This line](https://github.com/ChainSafe/nodewatch-api/blob/55bf484780fddaa3154c9b77d43833dcbdd0eee2/models/peer.go#L209) splits the `UserAgent` into it's parts based off of `/`, so if Lodestar's `UserAgent` is `Lodestar/0.41.0`, we'd be storing the Peer with `userAgent.Name = Lodestar` and `userAgent.version = 0.41.0`

**Comment by sadiq1971** [comment]
> From my understanding, no code change is required for how the crawler parses the `UserAgent`. [This line](https://github.com/ChainSafe/nodewatch-api/blob/55bf484780fddaa3154c9b77d43833dcbdd0eee2/models/peer.go#L209) splits the `UserAgent` into it's parts based off of `/`, so if Lodestar's `UserAgent` is `Lodestar/0.41.0`, we'd be storing the Peer with `userAgent.Name = Lodestar` and `userAgent.version = 0.41.0`

Right. Nothing required. I already tested this and Lodestar client was being parsed successfully.
