### ISSUE TITLE
Peer.PubKey uses incorrect format

### ISSUE THREAD

**Issue by phelps-sg** [ChainSafe/nodewatch-api#241]
## Expected Behavior

Peer.PubKey should be 48 bytes (96 hex characters) as seen in beaconcha.in

## Current Behavior

Whereas in the crawler DB it is only 32 bytes (64 hex characters).

## Possible Solution

ETH2 Validator public keys are BLS12-381 whereas nodewatch-api assumes they are Secp256k1.  See https://ethereum.stackexchange.com/questions/119315/public-keys-vs-addresses-on-eth2-beacon-chain

## Steps to Reproduce (for bugs)

1.  Look at a single validator in the mongoDB
2.  Copy public key field to clipboard
3.  Search for public key on beaconchai.in
4. No validator is found

## Versions
Eth2-Crawler commit (or docker tag): 5d26b852aa3f040cc7c11fe0816d156f55e99c62
Go version:

**Comment by sadiq1971** [comment]
You are mixing the validator's public key with the client's public key/public address. The crawler doesn't collect any info about the validator. A node/client may have many validators. Here crawler is getting the public key from the enr actually with this method:
https://github.com/ethereum/go-ethereum/blob/9afc6816d2301b52e01e0a1c84a933a879115571/p2p/enode/node.go#L132
Which is nothing but the secp256k1 public key of the node as mentioned in the comment.

**Comment by sadiq1971** [comment]
@Kiran1Kalidindi It is something that needs to be researched. You can create a different issue for that.
